class Messages:
    MESSAGE_FROM_STATE = {
        "/create_TaskList": "To create a new Task List provide following information:\n"
                           "Change \\_ for valid information.\n"
                           "Weight is optional. It is used to calculate progress of Workspace(More weight - more progress it brings after completion)\n"
                           "Description is optional.\n"
                           "You can copy the following for convenience\n"
                           "```\n"
                           "Workspace Name - _\n"
                           "Name - _\n"
                           "Description - _\n"
                           "Weight - _\n"
                           "```",
        "/create_Task": "To create a new Task provide following information:\n"
                       "Change \\_ for valid information\n"
                       "Weight is optional. It is used to calculate progress of Task List(More weight - more progress it brings after completion)\n"
                       "Description and Completed is optional.\n"
                       "You can copy the following for convenience\n"
                       "```\n"
                       "List Name - _\n"
                       "Name - _\n"
                       "Description - _\n"
                       "Weight - _\n"
                       "Completed - _\n"
                       "```"
    }
